# 1. Tensorflow test

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello tensorflow')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [4]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c]))
sess.close()

b'Hello tensorflow'
[10, 32, 42]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [6]:
x_data = [[1,2,3], [4,5,6]]

In [7]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [8]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [9]:
expr = tf.matmul(X, W) + b

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('=== x_data ===')
print(x_data)
print('=== W ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))
print('=== expr ===')
print(sess.run(expr, feed_dict={X: x_data}))

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.98480171 -0.03968684]
 [ 1.03819466 -0.57523274]
 [-0.58592558  1.36379087]]
=== b ===
[[ 0.28378397]
 [-1.8320415 ]]
=== expr ===
[[ 1.58719826  3.18500423]
 [ 3.78258538  3.31579232]]


In [27]:
sess.close()

# 2. Linear Regression by tensorflow

In [28]:
x_data = [1,2,3]
y_data = [1,2,3]

In [29]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [30]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [31]:
W

In [32]:
hypothesis = W * X + b

In [33]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [34]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [41]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, sess.run(W), sess.run(b))
    
    print('X:5, Y:', sess.run(hypothesis, feed_dict={X:5}))
    print('X:2.5, Y:', sess.run(hypothesis, feed_dict={X:2.5}))

0 0.286902 [ 0.88635105] [ 0.31851855]
1 0.0169319 [ 0.86501598] [ 0.3002744]
2 0.0130656 [ 0.87089133] [ 0.29421315]
3 0.0124084 [ 0.87370753] [ 0.28701401]
4 0.0118186 [ 0.87677491] [ 0.28012818]
5 0.0112571 [ 0.87973368] [ 0.27339256]
6 0.0107224 [ 0.88262516] [ 0.26682058]
7 0.0102131 [ 0.88544673] [ 0.26040637]
8 0.00972797 [ 0.88820058] [ 0.2541464]
9 0.0092659 [ 0.89088815] [ 0.24803688]
10 0.00882576 [ 0.89351112] [ 0.24207424]
11 0.00840652 [ 0.89607108] [ 0.23625495]
12 0.0080072 [ 0.89856941] [ 0.23057552]
13 0.00762685 [ 0.90100777] [ 0.22503266]
14 0.00726458 [ 0.90338749] [ 0.21962301]
15 0.00691951 [ 0.90570998] [ 0.21434341]
16 0.00659083 [ 0.90797669] [ 0.20919076]
17 0.00627775 [ 0.91018879] [ 0.20416193]
18 0.00597955 [ 0.91234779] [ 0.19925402]
19 0.00569552 [ 0.91445488] [ 0.1944641]
20 0.00542498 [ 0.91651136] [ 0.18978932]
21 0.00516729 [ 0.91851836] [ 0.1852269]
22 0.00492183 [ 0.92047715] [ 0.18077418]
23 0.00468805 [ 0.92238879] [ 0.17642848]
24 0.00446536 [ 0