In [9]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import tree
from IPython.display import Image
import pandas as pd
import numpy as np
import pydotplus
import os

In [112]:
csv_path = os.path.abspath(os.path.join(os.pardir))+'/dataset/toy_data/tennis.csv'

In [113]:
tennis_data = pd.read_csv(csv_path)

In [114]:
tennis_data

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [115]:
tennis_data.outlook = tennis_data.outlook.replace('sunny', 0)

In [116]:
tennis_data.outlook = tennis_data.outlook.replace('overcast', 1)

In [117]:
tennis_data.outlook = tennis_data.outlook.replace('rainy', 2)

In [118]:
tennis_data.temp = tennis_data.temp.replace('hot', 3)

In [119]:
tennis_data.temp = tennis_data.temp.replace('mild', 4)

In [120]:
tennis_data.temp = tennis_data.temp.replace('cool', 5)

In [121]:
tennis_data.humidity = tennis_data.humidity.replace('high', 6)

In [122]:
tennis_data.humidity = tennis_data.humidity.replace('normal', 7)

In [142]:
tennis_data.windy = tennis_data.windy.astype(str)

In [143]:
tennis_data.windy = tennis_data.windy.replace('False', 8)

In [144]:
tennis_data.windy = tennis_data.windy.replace('True', 9)

In [145]:
tennis_data.play = tennis_data.play.replace('no', 10)

In [146]:
tennis_data.play = tennis_data.play.replace('yes', 11)

In [147]:
X=np.array(pd.DataFrame(tennis_data, columns=['outlook', 'temp', 'humidity', 'windy']))

In [148]:
X

array([[0, 3, 6, 8],
       [0, 3, 6, 9],
       [1, 3, 6, 8],
       [2, 4, 6, 8],
       [2, 5, 7, 8],
       [2, 5, 7, 9],
       [1, 5, 7, 9],
       [0, 4, 6, 8],
       [0, 5, 7, 8],
       [2, 4, 7, 8],
       [0, 4, 7, 9],
       [1, 4, 6, 9],
       [1, 3, 7, 8],
       [2, 4, 6, 9]])

In [149]:
y = np.array(pd.DataFrame(tennis_data, columns = ['play']))

In [150]:
y

array([[10],
       [10],
       [11],
       [11],
       [11],
       [10],
       [11],
       [10],
       [11],
       [11],
       [11],
       [11],
       [11],
       [10]])

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [164]:
X_train

array([[2, 4, 6, 8],
       [0, 3, 6, 9],
       [1, 5, 7, 9],
       [0, 5, 7, 8],
       [1, 3, 7, 8],
       [2, 5, 7, 9],
       [1, 3, 6, 8],
       [1, 4, 6, 9],
       [2, 4, 6, 9],
       [0, 4, 6, 8]])

In [165]:
X_test

array([[2, 4, 7, 8],
       [0, 4, 7, 9],
       [0, 3, 6, 8],
       [2, 5, 7, 8]])

In [166]:
y_train

array([[11],
       [10],
       [11],
       [11],
       [11],
       [10],
       [11],
       [11],
       [10],
       [10]])

In [167]:
y_test

array([[11],
       [11],
       [10],
       [11]])

In [168]:
dt_clf=tree.DecisionTreeClassifier()

In [169]:
dt_clf = dt_clf.fit(X_train, y_train)

In [170]:
dt_clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [171]:
dt_prediction = dt_clf.predict(X_test)

In [172]:
dt_prediction

array([11, 11, 10, 11])

In [173]:
print(confusion_matrix(y_test, dt_prediction))

[[1 0]
 [0 3]]


In [174]:
print(classification_report(y_test, dt_prediction))

             precision    recall  f1-score   support

         10       1.00      1.00      1.00         1
         11       1.00      1.00      1.00         3

avg / total       1.00      1.00      1.00         4

